project_name: terraform-provider-yggdrasil
builds:
  - id: provider
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
archives:
  - id: archive
    builds: [provider]
    format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
